apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-demo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "devops-demo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "devops-demo.name" . }}
    spec:
      containers:
        - name: devops-demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "{{ .Values.env.APP_VERSION }}"
            - name: ENV
              value: "{{ .Values.env.ENV }}"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
