apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "devops-demo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: {{ include "devops-demo.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "devops-demo.name" . }}
    spec:
      serviceAccountName: devops-demo-sa 
      
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: APP_VERSION
          value: "{{ .Values.env.APP_VERSION }}"

  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: { duration: 30s }
      - setWeight: 30
      - pause: { duration: 30s }
      - setWeight: 60
      - pause: { duration: 30s }
      - setWeight: 100
